#! /bin/sh
#
# Example panel for lemonbar

. panel_colors

while read -r line ; do
	case $line in
		S*)
			# clock output
			sys="${line#?}"
			;;
		C*)
			# conky output
			conky="${line#?}"
			;;
	esac
	printf "%s\n" "| %{l}${sys}%{r}${conky}"
done
